spring:
  application:
    name: texas

  cloud:
    inetutils:
      preferred-networks: 127.0.0.1
    openfeign:
      client:
        config:
          open-meteo-forecast-client:
            defaultQueryParameters:
              current: "temperature_2m,relative_humidity_2m,apparent_temperature,precipitation_probability,rain,wind_speed_10m,wind_direction_10m,weather_code,cloud_cover,is_day,pressure_msl"
              daily: "weather_code,temperature_2m_max,precipitation_probability_max,temperature_2m_min"
              hourly: "weather_code,temperature_2m,precipitation_probability,is_day"
              precipitation_unit: inch
              temperature_unit: fahrenheit
              wind_speed_unit: mph
              timezone: America/Chicago
              past_days: 1
          open-meteo-historical-client:
            defaultQueryParameters:
              daily: "weather_code,temperature_2m_max,temperature_2m_min,sunrise,sunset,precipitation_sum,wind_speed_10m_mean,wind_direction_10m_dominant,relative_humidity_2m_mean,cloud_cover_mean,pressure_msl_mean"
              precipitation_unit: inch
              temperature_unit: fahrenheit
              wind_speed_unit: mph
              timezone: America/Chicago

  data:
    mongodb:
      host: localhost
      port: 27017
      database: texas

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

app:
  check-distance: 0.00045
  city-camera-limit: 8

spring.mvc.view.prefix: /WEB-INF/views
spring.mvc.view.suffix: .jsp
logging.file.name: /var/log/texas/texas.log
server.address: 0.0.0.0